<?php
namespace Boparaiamrit\Twitter;


interface ITwitterClient
{
	const CONSUMER_KEY        = 'CONSUMER_KEY';
	const CONSUMER_SECRET     = 'CONSUMER_SECRET';
	const ACCESS_TOKEN        = 'ACCESS_TOKEN';
	const ACCESS_TOKEN_SECRET = 'ACCESS_TOKEN_SECRET';
	const AUTHORIZE_ROUTE     = 'AUTHORIZE_ROUTE';
	const AUTHENTICATE_ROUTE  = 'AUTHENTICATE_ROUTE';
	const ACCESS_TOKEN_ROUTE  = 'ACCESS_TOKEN_ROUTE';
	const REQUEST_TOKEN_ROUTE = 'REQUEST_TOKEN_ROUTE';
	const OUATH_CALLBACK_URL  = 'OUATH_CALLBACK_URL';
}
